Algoritmo "Primeiro programa"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Jose Vasconcelos
// Data atual  : 12-08-2022

Var

a,b : inteiro

INICIO
.
escreva("Digite a")
leia(a)
escreva("Dgitie b")
leia(b)
escreval("Valor 1: ",a)      //"escreval" escreve na tela e o que vier a seguir fica na linha de baixo
escreva("Valor 2: ",b)
Fimalgoritmo